# Short-cut for updating functional tests.
# Don't run until every file has been manually inspected and differences explained
cp ../../test_results/bench_unroll/fn.vcf.gz ./bench/bench_unroll/fn.vcf.gz
cp ../../test_results/bench_unroll/fp.vcf.gz ./bench/bench_unroll/fp.vcf.gz
cp ../../test_results/bench_unroll/tp-base.vcf.gz ./bench/bench_unroll/tp-base.vcf.gz
cp ../../test_results/bench_unroll/tp-comp.vcf.gz ./bench/bench_unroll/tp-comp.vcf.gz
cp ../../test_results/bench13_extend/fn.vcf.gz ./bench/bench13_extend/fn.vcf.gz
cp ../../test_results/bench13_extend/fp.vcf.gz ./bench/bench13_extend/fp.vcf.gz
cp ../../test_results/bench13_extend/tp-base.vcf.gz ./bench/bench13_extend/tp-base.vcf.gz
cp ../../test_results/bench13_extend/tp-comp.vcf.gz ./bench/bench13_extend/tp-comp.vcf.gz
cp ../../test_results/bench13/fn.vcf.gz ./bench/bench13/fn.vcf.gz
cp ../../test_results/bench13/fp.vcf.gz ./bench/bench13/fp.vcf.gz
cp ../../test_results/bench13/tp-base.vcf.gz ./bench/bench13/tp-base.vcf.gz
cp ../../test_results/bench13/tp-comp.vcf.gz ./bench/bench13/tp-comp.vcf.gz
cp ../../test_results/bench_gtcomp_edgecase1/fn.vcf.gz ./bench/bench_gtcomp_edgecase1/fn.vcf.gz
cp ../../test_results/bench_gtcomp_edgecase1/fp.vcf.gz ./bench/bench_gtcomp_edgecase1/fp.vcf.gz
cp ../../test_results/bench_gtcomp_edgecase1/tp-base.vcf.gz ./bench/bench_gtcomp_edgecase1/tp-base.vcf.gz
cp ../../test_results/bench_gtcomp_edgecase1/tp-comp.vcf.gz ./bench/bench_gtcomp_edgecase1/tp-comp.vcf.gz
cp ../../test_results/bench12/fn.vcf.gz ./bench/bench12/fn.vcf.gz
cp ../../test_results/bench12/fp.vcf.gz ./bench/bench12/fp.vcf.gz
cp ../../test_results/bench12/tp-base.vcf.gz ./bench/bench12/tp-base.vcf.gz
cp ../../test_results/bench12/tp-comp.vcf.gz ./bench/bench12/tp-comp.vcf.gz
cp ../../test_results/bench23/fn.vcf.gz ./bench/bench23/fn.vcf.gz
cp ../../test_results/bench23/fp.vcf.gz ./bench/bench23/fp.vcf.gz
cp ../../test_results/bench23/tp-base.vcf.gz ./bench/bench23/tp-base.vcf.gz
cp ../../test_results/bench23/tp-comp.vcf.gz ./bench/bench23/tp-comp.vcf.gz
cp ../../test_results/bench_starallele/fn.vcf.gz ./bench/bench_starallele/fn.vcf.gz
cp ../../test_results/bench_starallele/fp.vcf.gz ./bench/bench_starallele/fp.vcf.gz
cp ../../test_results/bench_starallele/tp-base.vcf.gz ./bench/bench_starallele/tp-base.vcf.gz
cp ../../test_results/bench_starallele/tp-comp.vcf.gz ./bench/bench_starallele/tp-comp.vcf.gz
cp ../../test_results/bench12_gtcomp/fn.vcf.gz ./bench/bench12_gtcomp/fn.vcf.gz
cp ../../test_results/bench12_gtcomp/fp.vcf.gz ./bench/bench12_gtcomp/fp.vcf.gz
cp ../../test_results/bench12_gtcomp/tp-base.vcf.gz ./bench/bench12_gtcomp/tp-base.vcf.gz
cp ../../test_results/bench12_gtcomp/tp-comp.vcf.gz ./bench/bench12_gtcomp/tp-comp.vcf.gz
cp ../../test_results/bench13_includebed/fn.vcf.gz ./bench/bench13_includebed/fn.vcf.gz
cp ../../test_results/bench13_includebed/fp.vcf.gz ./bench/bench13_includebed/fp.vcf.gz
cp ../../test_results/bench13_includebed/tp-base.vcf.gz ./bench/bench13_includebed/tp-base.vcf.gz
cp ../../test_results/bench13_includebed/tp-comp.vcf.gz ./bench/bench13_includebed/tp-comp.vcf.gz
cp ../../test_results/divided/multi_00000020.vcf.gz ./divide/divided/multi_00000020.vcf.gz
cp ../../test_results/divided/multi_00000004.vcf.gz ./divide/divided/multi_00000004.vcf.gz
cp ../../test_results/divided/multi_00000008.vcf.gz ./divide/divided/multi_00000008.vcf.gz
cp ../../test_results/divided/multi_00000016.vcf.gz ./divide/divided/multi_00000016.vcf.gz
cp ../../test_results/divided/multi_00000022.vcf.gz ./divide/divided/multi_00000022.vcf.gz
cp ../../test_results/divided/multi_00000014.vcf.gz ./divide/divided/multi_00000014.vcf.gz
cp ../../test_results/divided/multi_00000006.vcf.gz ./divide/divided/multi_00000006.vcf.gz
cp ../../test_results/divided/multi_00000018.vcf.gz ./divide/divided/multi_00000018.vcf.gz
cp ../../test_results/divided/multi_00000002.vcf.gz ./divide/divided/multi_00000002.vcf.gz
cp ../../test_results/divided/multi_00000010.vcf.gz ./divide/divided/multi_00000010.vcf.gz
cp ../../test_results/divided/multi_00000012.vcf.gz ./divide/divided/multi_00000012.vcf.gz
cp ../../test_results/divided/multi_00000000.vcf.gz ./divide/divided/multi_00000000.vcf.gz
cp ../../test_results/divided/multi_00000005.vcf.gz ./divide/divided/multi_00000005.vcf.gz
cp ../../test_results/divided/multi_00000017.vcf.gz ./divide/divided/multi_00000017.vcf.gz
cp ../../test_results/divided/multi_00000009.vcf.gz ./divide/divided/multi_00000009.vcf.gz
cp ../../test_results/divided/multi_00000021.vcf.gz ./divide/divided/multi_00000021.vcf.gz
cp ../../test_results/divided/multi_00000015.vcf.gz ./divide/divided/multi_00000015.vcf.gz
cp ../../test_results/divided/multi_00000019.vcf.gz ./divide/divided/multi_00000019.vcf.gz
cp ../../test_results/divided/multi_00000007.vcf.gz ./divide/divided/multi_00000007.vcf.gz
cp ../../test_results/divided/multi_00000003.vcf.gz ./divide/divided/multi_00000003.vcf.gz
cp ../../test_results/divided/multi_00000011.vcf.gz ./divide/divided/multi_00000011.vcf.gz
cp ../../test_results/divided/multi_00000013.vcf.gz ./divide/divided/multi_00000013.vcf.gz
cp ../../test_results/divided/multi_00000001.vcf.gz ./divide/divided/multi_00000001.vcf.gz
cp ../../test_results/ga4gh_withrefine_truth.vcf.gz ./ga4gh/ga4gh_withrefine_truth.vcf.gz
cp ../../test_results/ga4gh_norefine_truth.vcf.gz ./ga4gh/ga4gh_norefine_truth.vcf.gz
cp ../../test_results/ga4gh_norefine_query.vcf.gz ./ga4gh/ga4gh_norefine_query.vcf.gz
cp ../../test_results/ga4gh_withrefine_query.vcf.gz ./ga4gh/ga4gh_withrefine_query.vcf.gz
cp ../../test_results/phab_result.vcf.gz ./phab/phab_result.vcf.gz
cp ../../test_results/phab_result_wfa.vcf.gz ./phab/phab_result_wfa.vcf.gz
cp ../../test_results/phab_result_poa.vcf.gz ./phab/phab_result_poa.vcf.gz
cp ../../test_results/refine_output_one/fn.vcf.gz ./refine/refine_output_one/fn.vcf.gz
cp ../../test_results/refine_output_one/fp.vcf.gz ./refine/refine_output_one/fp.vcf.gz
cp ../../test_results/refine_output_one/phab.output.vcf.gz ./refine/refine_output_one/phab.output.vcf.gz
cp ../../test_results/refine_output_one/tp-base.vcf.gz ./refine/refine_output_one/tp-base.vcf.gz
cp ../../test_results/refine_output_one/phab_bench/fn.vcf.gz ./refine/refine_output_one/phab_bench/fn.vcf.gz
cp ../../test_results/refine_output_one/phab_bench/fp.vcf.gz ./refine/refine_output_one/phab_bench/fp.vcf.gz
cp ../../test_results/refine_output_one/phab_bench/tp-base.vcf.gz ./refine/refine_output_one/phab_bench/tp-base.vcf.gz
cp ../../test_results/refine_output_one/phab_bench/tp-comp.vcf.gz ./refine/refine_output_one/phab_bench/tp-comp.vcf.gz
cp ../../test_results/refine_output_one/tp-comp.vcf.gz ./refine/refine_output_one/tp-comp.vcf.gz
cp ../../test_results/refine_output_two/fn.vcf.gz ./refine/refine_output_two/fn.vcf.gz
cp ../../test_results/refine_output_two/fp.vcf.gz ./refine/refine_output_two/fp.vcf.gz
cp ../../test_results/refine_output_two/phab.output.vcf.gz ./refine/refine_output_two/phab.output.vcf.gz
cp ../../test_results/refine_output_two/tp-base.vcf.gz ./refine/refine_output_two/tp-base.vcf.gz
cp ../../test_results/refine_output_two/phab_bench/fn.vcf.gz ./refine/refine_output_two/phab_bench/fn.vcf.gz
cp ../../test_results/refine_output_two/phab_bench/fp.vcf.gz ./refine/refine_output_two/phab_bench/fp.vcf.gz
cp ../../test_results/refine_output_two/phab_bench/tp-base.vcf.gz ./refine/refine_output_two/phab_bench/tp-base.vcf.gz
cp ../../test_results/refine_output_two/phab_bench/tp-comp.vcf.gz ./refine/refine_output_two/phab_bench/tp-comp.vcf.gz
cp ../../test_results/refine_output_two/tp-comp.vcf.gz ./refine/refine_output_two/tp-comp.vcf.gz
cp ../../test_results/refine_output_three/fn.vcf.gz ./refine/refine_output_three/fn.vcf.gz
cp ../../test_results/refine_output_three/fp.vcf.gz ./refine/refine_output_three/fp.vcf.gz
cp ../../test_results/refine_output_three/phab.output.vcf.gz ./refine/refine_output_three/phab.output.vcf.gz
cp ../../test_results/refine_output_three/tp-base.vcf.gz ./refine/refine_output_three/tp-base.vcf.gz
cp ../../test_results/refine_output_three/phab_bench/fn.vcf.gz ./refine/refine_output_three/phab_bench/fn.vcf.gz
cp ../../test_results/refine_output_three/phab_bench/fp.vcf.gz ./refine/refine_output_three/phab_bench/fp.vcf.gz
cp ../../test_results/refine_output_three/phab_bench/tp-base.vcf.gz ./refine/refine_output_three/phab_bench/tp-base.vcf.gz
cp ../../test_results/refine_output_three/phab_bench/tp-comp.vcf.gz ./refine/refine_output_three/phab_bench/tp-comp.vcf.gz
cp ../../test_results/refine_output_three/tp-comp.vcf.gz ./refine/refine_output_three/tp-comp.vcf.gz
cp ../../test_results/input1_collapsed.vcf ./collapse/
cp ../../test_results/input1_median_collapsed.vcf ./collapse/
cp ../../test_results/input2_collapsed.vcf ./collapse/
cp ../../test_results/input3_collapsed.vcf ./collapse/
cp ../../test_results/inputintragt_collapsed.vcf ./collapse/
cp ../../test_results/inputintragth_collapsed.vcf ./collapse/
cp ../../test_results/inputissue196_collapsed.vcf ./collapse/
cp ../../test_results/input1_median_removed.vcf ./collapse/
cp ../../test_results/input1_removed.vcf ./collapse/
cp ../../test_results/input2_removed.vcf ./collapse/
cp ../../test_results/input3_removed.vcf ./collapse/
cp ../../test_results/inputintragt_removed.vcf ./collapse/
cp ../../test_results/inputintragth_removed.vcf ./collapse/
cp ../../test_results/inputissue196_removed.vcf ./collapse/
cp ../../test_results/multi_removed_first.vcf ./collapse/multi_removed_first.vcf
cp ../../test_results/multi_collapsed_first.vcf ./collapse/multi_collapsed_first.vcf
cp ../../test_results/multi_removed_common.vcf  ./collapse/multi_removed_common.vcf
cp ../../test_results/multi_collapsed_common.vcf  ./collapse/multi_collapsed_common.vcf
cp ../../test_results/multi_removed_maxqual.vcf  ./collapse/multi_removed_maxqual.vcf
cp ../../test_results/multi_collapsed_maxqual.vcf  ./collapse/multi_collapsed_maxqual.vcf
