name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
          key: pipcache
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install anybadge
          python setup.py install
      - name: Analysing the code with pylint
        run: |
          python repo_utils/pylint_maker.py
      - name: commit rendered README
        run: |
          git add imgs/pylint.svg
          git commit -m "Update pylint score" || echo "No changes to commit"
          git push origin $GITHUB_REF || echo "No changes to commit"
